<template>
  <div class="container-fluid">
    <!-- Hamburger button for medium devices -->
   <HemBurger @click="toggleSidebar"/>
    <div class="row">
      
      <!-- Sidebar with conditional classes -->
        <SideBar :class="{'d-none': sidebarOpen && isMobile}" />
      
      <!-- Main Content -->
      <div :class="['main-content', sidebarOpen || !isMobile ? 'col-md-10' : 'col-12']">
        <div class="d-flex justify-content-between align-items-center mb-4">
          <h5>Dashboard</h5>
          <div>
            <router-link to="/invoices/create" class="btn btn-primary rounded-pill">
              Create Invoice
            </router-link>
          </div>
        </div>
        
        <div class="row">
          <div class="col-md-4">
            <div class="card mb-4">
              <div class="card-body py-4">
                <p class="card-title fw-semibold fs-6">Total Invoices</p>
                <h5 class="card-text text-primary">{{ invoices.length }}</h5>
              </div>
            </div>
          </div>
          
          <div class="col-md-4">
            <div class="card mb-4">
              <div class="card-body py-4">
                <p class="card-title fw-semibold fs-6">User Generated</p>
                <h5 class="card-text text-primary">{{ userGenerated }}</h5>
              </div>
            </div>
          </div>
          
          <div class="col-md-4">
            <div class="card mb-4">
              <div class="card-body py-4">
                <p class="card-title fw-semibold fs-6">Panel Generated</p>
                <h5 class="card-text text-primary">{{ panelGenerated }}</h5>
              </div>
            </div>
          </div>
        </div>
        
        <div class="card">
          <div class="card-header">
            <h5 class="mb-0">Recent Invoices</h5>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-hover">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>Date</th>
                    <th>Customer</th>
                    <th>Amount</th>
                    <th>Generated By</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  <tr v-for="invoice in recentInvoices" :key="invoice._id">
                    <td>{{ invoice._id }}</td>
                    <td>{{ formatDate(invoice.createdAt) }}</td>
                    <td>{{ invoice.invoiceToDetails.name }}</td>
                    <td>₹{{ invoice.total }}</td>
                    <td>
                      <span :class="invoice.generatedBy === 'User' ? 'badge bg-primary px-3 py-2 rounded-pill' : 'badge bg-info'">
                        {{ invoice.generatedBy }}
                      </span>
                    </td>
                    <td>
                      <div class="btn-group">
                        <button class="btn btn-sm btn-outline-primary me-1" @click="viewInvoiceDetails(invoice)">
                          <i class="bi bi-eye"></i>
                        </button>
                        <button class="btn btn-sm btn-outline-danger" @click="deleteInvoice(invoice._id)">
                          <i class="bi bi-trash"></i>
                        </button>
                      </div>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
        
        <!-- Invoice Details Modal -->
        <div class="modal fade" id="invoiceDetailsModal" tabindex="-1" aria-labelledby="invoiceDetailsModalLabel" aria-hidden="true">
          <div class="modal-dialog modal-lg">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="invoiceDetailsModalLabel">Invoice Details</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body" v-if="selectedInvoice">
                <div class="row mb-4">
                  <div class="col-md-6">
                    <h6 class="fw-bold">Invoice Number</h6>
                    <p>{{ selectedInvoice.invoiceNumber || selectedInvoice._id }}</p>
                    
                    <h6 class="fw-bold mt-3">Date</h6>
                    <p>{{ formatDate(selectedInvoice.createdAt) }}</p>
                    
                    <h6 class="fw-bold mt-3">Generated By</h6>
                    <p>
                      <span :class="selectedInvoice.generatedBy === 'User' ? 'badge bg-primary' : 'badge bg-info'">
                        {{ selectedInvoice.generatedBy }}
                      </span>
                    </p>
                  </div>
                  <div class="col-md-6">
                    <h6 class="fw-bold">Company Details</h6>
                    <p class="mb-1">{{ selectedInvoice.companyDetails.name }}</p>
                    <p class="mb-1">{{ selectedInvoice.companyDetails.email }}</p>
                    <p class="mb-1">{{ selectedInvoice.companyDetails.mobile }}</p>
                    <p class="mb-1">{{ selectedInvoice.companyDetails.address }}</p>
                    <p v-if="selectedInvoice.companyDetails.gstin">GSTIN: {{ selectedInvoice.companyDetails.gstin }}</p>
                  </div>
                </div>
                
                <div class="row mb-4">
                  <div class="col-12">
                    <h6 class="fw-bold">Customer Details</h6>
                    <p class="mb-1">{{ selectedInvoice.invoiceToDetails.name }}</p>
                    <p class="mb-1">{{ selectedInvoice.invoiceToDetails.email }}</p>
                    <p class="mb-1">{{ selectedInvoice.invoiceToDetails.mobile }}</p>
                    <p class="mb-1">{{ selectedInvoice.invoiceToDetails.address }}, {{ selectedInvoice.invoiceToDetails.city }}, {{ selectedInvoice.invoiceToDetails.state }} - {{ selectedInvoice.invoiceToDetails.pincode }}</p>
                  </div>
                </div>
                
                <h6 class="fw-bold">Transaction Details</h6>
                <div class="table-responsive">
                  <table class="table table-bordered">
                    <thead>
                      <tr>
                        <th>Product/Service</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Discount</th>
                        <th>Total</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr v-for="(item, index) in selectedInvoice.transactionDetails" :key="index">
                        <td>{{ item.product }}</td>
                        <td>₹{{ item.rate }}</td>
                        <td>{{ item.quantity }}</td>
                        <td>₹{{ item.discount }}</td>
                        <td>₹{{ item.total }}</td>
                      </tr>
                    </tbody>
                    <tfoot>
                      <tr>
                        <td colspan="4" class="text-end fw-bold">Grand Total:</td>
                        <td class="fw-bold">₹{{ selectedInvoice.total }}</td>
                      </tr>
                    </tfoot>
                  </table>
                </div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { mapGetters } from 'vuex'
import SideBar from '../components/SideBar.vue'
import HemBurger from '../components/Hemburger.vue'

export default {
  name: 'Dashboard',
  components: {
    SideBar,
    HemBurger
  },
  data() {
    return {
      selectedInvoice: null,
      modal: null,
      sidebarOpen: true,
      isMobile: false
    }
  },
  computed: {
    ...mapGetters({
      invoices: 'invoice/allInvoices',
      user: 'auth/user'
    }),
    userGenerated() {
      return this.invoices.filter(invoice => invoice.generatedBy === 'User').length
    },
    panelGenerated() {
      return this.invoices.filter(invoice => invoice.generatedBy === 'Panel').length
    },
    recentInvoices() {
      return [...this.invoices].slice(0, 5)
    }
  },
  methods: {
    toggleSidebar() {
      this.sidebarOpen = !this.sidebarOpen;
    },
    checkScreenSize() {
      this.isMobile = window.innerWidth < 768;
      // On larger screens, sidebar should always be visible
      if (!this.isMobile) {
        this.sidebarOpen = true;
      }
    },
    logout() {
      this.$store.dispatch('auth/logout')
    },
    formatDate(dateString) {
      const date = new Date(dateString)
      return date.toLocaleDateString('en-GB', {
        day: '2-digit',
        month: '2-digit',
        year: 'numeric'
      })
    },
    viewInvoiceDetails(invoice) {
      this.selectedInvoice = invoice
      this.modal.show()
    },
    
    deleteInvoice(id) {
      if (confirm('Are you sure you want to delete this invoice?')) {
        this.$store.dispatch('invoice/deleteInvoice', id)
          .then(() => {
            // Refresh the invoices list after deletion
            this.$store.dispatch('invoice/fetchInvoices')
          })
          .catch(error => {
            console.error('Error deleting invoice:', error)
          })
      }
    }
  },
  created() {
    this.$store.dispatch('invoice/fetchInvoices')
  },
  mounted() {
    // Initialize Bootstrap modal
    this.modal = new bootstrap.Modal(document.getElementById('invoiceDetailsModal'))
    
    // Check screen size on mount
    this.checkScreenSize();
    
    // Add resize event listener
    window.addEventListener('resize', this.checkScreenSize);
  },
  beforeDestroy() {
    // Clean up event listener
    window.removeEventListener('resize', this.checkScreenSize);
  }
}
</script>

<style scoped>
.modal h6 {
  font-size: 14px;
  font-weight: 600
}
.modal p {
  font-size: 13px;
  font-weight: 600;
}
.table th {
  white-space: nowrap;
}
.table tr th {
  font-size: 12px;
  background: #CBE0EF;
  padding: 20px 8px;
}
.table tr td {
  font-size: 12.5px;
  font-weight: bold;
  padding: 30px 8px;
}



@media (max-width: 767.98px) {
  .main-content {
    padding-top: 60px;
  }
}
</style>
