<template>
  <div class="container-fluid">
    <!-- Hamburger button for medium devices -->
  <HemBurger @click="toggleSidebar" />
    <div class="row">
      
      <!-- Sidebar with conditional classes -->
        <SideBar :class="{'d-none': sidebarOpen && isMobile}" />

      <!-- Main Content -->
      <div :class="['main-content', sidebarOpen || !isMobile ? 'col-md-10' : 'col-12', 'pt-0', 'p-md-0']">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-sm-evenly justify-content-md-between bg-white invoice-nav mb-3 p-2">
          <h5>Invoice List</h5>
          <div class="search-input">
            <div class="input-group">
              <span class="input-group-text bg-transparent">
                <i class="bi bi-search"></i>
              </span>
              <input type="text" class="form-control" placeholder="Search by name, email, mobile or invoice number..."
                v-model="searchQuery" @input="updateSearchQuery">
            </div>
          </div>
        
      </div>
      <div class="justify-content-between align-items-center mb-4">

        <div class="d-flex flex-wrap filteration justify-content-center justify-content-sm-between">
          <button class="btn bg-white border bg-light text-dark border rounded mx-md-3" @click="showFilters = !showFilters">
             Generated by filter &nbsp; &nbsp; &nbsp;  <i class="bi bi-chevron-down"></i>
          </button>
          <router-link to="/invoices/create" class="btn btn-primary rounded-pill">
           Create Invoice
          </router-link>
        </div>
      </div>

      <!-- Advanced Filters -->
      <div class="card mb-4" v-if="showFilters">
        <div class="card-body">
          <div class="row">
            <!-- Search -->
            <div class="col-md-12 mb-3">
              <div class="serach-input input-group">
                <span class="input-group-text">
                  <i class="bi bi-search"></i>
                </span>
                <input type="text" class="form-control" placeholder="Search by name, email, mobile or invoice number..."
                  v-model="searchQuery" @input="updateSearchQuery">
              </div>
            </div>

            <!-- Date Range -->
            <div class="col-md-6 mb-3">
              <label class="form-label">Date Range</label>
              <div class="d-flex gap-2">
                <!-- <input type="date" class="form-control" v-model="dateRange.start" @change="updateDateRange" 
                       :min="minDate" :max="dateRange.end || maxDate" placeholder="Start Date"> -->
                       <input type="date" class="form-control" v-model="dateRange.start" @change="updateDateRange">
                <input type="date" class="form-control" v-model="dateRange.end" @change="updateDateRange"
                       :min="dateRange.start || minDate" :max="maxDate" placeholder="End Date">
              </div>
            </div>
            
        
            
            <!-- States -->
            <div class="col-md-12 mb-3">
              <label class="form-label">States</label>
              <div class="d-flex flex-wrap gap-2">
                <button v-for="state in availableStates" :key="state" class="btn btn-sm"
                  :class="selectedStates.includes(state) ? 'btn-primary' : 'btn-outline-primary'"
                  @click="toggleState(state)">
                  {{ state }}
                </button>
              </div>
            </div>

            <!-- Clear Filters -->
            <div class="col-md-12">
              <button class="btn btn-outline-danger" @click="clearFilters">
                <i class="bi bi-x-lg me-2"></i> Clear Filters
              </button>
            </div>
          </div>
        </div>
      </div>

      <div class="card border-0">
        <div class="card-body">
          <div class="row">
            <div class="col-md-4 py-4 bg-primary">
              <h5 class="mb-2 mt-2">{{ invoices.length }}</h5>
              <p class="mb-3 fw-bold text">Total</p>
            </div>
            <div class="col-md-4 py-4">
              <h5 class="mb-2 mt-2">{{ userGenerated }}</h5>
              <p class="mb-3 fw-bold text">User Generated</p>
            </div>
            <div class="col-md-4 py-4">
              <h5 class="mb-2 mt-2">{{ panelGenerated }}</h5>
              <p class="mb-3 fw-bold text">Panel Generated</p>
            </div>
          </div>
        </div>
      </div>

      <div class="card border-0">
        <!-- <div class="card-header">
          <ul class="nav nav-tabs card-header-tabs">
            <li class="nav-item">
              <a class="nav-link" :class="{ active: currentFilter === 'all' }" href="#"
                @click.prevent="setFilter('all')">
                All
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" :class="{ active: currentFilter === 'user' }" href="#"
                @click.prevent="setFilter('user')">
                User Generated
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" :class="{ active: currentFilter === 'panel' }" href="#"
                @click.prevent="setFilter('panel')">
                Panel Generated
              </a>
            </li>
          </ul>
        </div> -->
        <div class="card-body p-0">
          <div v-if="isLoading" class="text-center py-5">
            <div class="spinner-border text-primary" role="status">
              <span class="visually-hidden">Loading...</span>
            </div>
            <p class="mt-2">Loading invoices...</p>
          </div>

          <div v-else-if="error" class="alert alert-danger">
            <i class="bi bi-exclamation-triangle-fill me-2"></i>
            {{ error }}
            <button class="btn btn-sm btn-outline-danger ms-2" @click="fetchInvoices">
              <i class="bi bi-arrow-clockwise"></i> Retry
            </button>
          </div>

          <div v-else class="table-responsive">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th>ID</th>
                  <th>Initiated On</th>
                  <th>Generated By</th>
                  <th>Customer Name</th>
                  <!-- <th>Total Amount</th> -->
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="invoice in filteredInvoices" :key="invoice._id">
                  <td>{{ invoice.invoiceNumber ? invoice.invoiceNumber.slice(-1) : invoice._id.slice(-1) }}</td>
                  <td>
                    {{ formatDate(invoice.createdAt).date }}<br>
                    {{ formatDate(invoice.createdAt).time }}
                  </td>
                  <td>
                    <span>
                      {{ invoice.generatedBy }}
                    </span>
                  </td>
                  <td>
                    {{ invoice.invoiceToDetails.name }}<br>
                    {{ invoice.invoiceToDetails.mobile }}
                  </td>
                  <!-- <td>₹{{ invoice.total }}</td> -->
                  <td>
                    <div class="btn-group">
                      <router-link :to="`/invoices/edit/${invoice._id}`" class="btn btn-sm edit-btn btn-outline-primary px-3">
                      Edit
                      </router-link>
                    </div>
                  </td>
                </tr>
                <tr v-if="filteredInvoices.length === 0">
                  <td colspan="6" class="text-center py-4">
                    <i class="bi bi-inbox text-muted fs-1 d-block mb-2"></i>
                    <p class="text-muted mb-0">No invoices found matching your filters</p>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>
</template>

<script>
import { mapGetters, mapState } from 'vuex'
import SideBar from '../components/SideBar.vue'
import HemBurger from '../components/Hemburger.vue'

export default {
  name: 'InvoiceList',
  components: {
    SideBar,
    HemBurger
  },
  data() {
    return {
      showFilters: false,
      searchQuery: '',
      dateRange: {
        start: '',
        end: ''
      },
      isLoading: false,
      sidebarOpen: true,
      isMobile: false
    }
  },
  computed: {
    ...mapGetters({
      invoices: 'invoice/allInvoices',
      filteredInvoices: 'invoice/filteredInvoices',
      currentFilter: 'invoice/currentFilter',
      availableStates: 'invoice/availableStates',
      selectedStates: 'invoice/selectedStates'
    }),
    ...mapState({
      loading: state => state.invoice.loading,
      error: state => state.invoice.error
    }),
    // minDate() {
    //   if (this.invoices.length === 0) return '';
    //   return this.invoices.reduce((min, invoice) => {
    //     const date = new Date(invoice.createdAt);
    //     return date < new Date(min) ? date.toISOString().split('T')[0] : min;
    //   }, new Date().toISOString().split('T')[0]);
    // },
    maxDate() {
      if (this.invoices.length === 0) return '';
      return this.invoices.reduce((max, invoice) => {
        const date = new Date(invoice.createdAt);
        return date > new Date(max) ? date.toISOString().split('T')[0] : max;
      }, '1970-01-01');
    },
    userGenerated() {
      return this.invoices.filter(invoice => invoice.generatedBy === 'User').length
    },
    panelGenerated() {
      return this.invoices.filter(invoice => invoice.generatedBy === 'Panel').length
    }
  },
  methods: {
    toggleSidebar() {
      this.sidebarOpen = !this.sidebarOpen;
    },
    checkScreenSize() {
      this.isMobile = window.innerWidth < 768;
      // On larger screens, sidebar should always be visible
      if (!this.isMobile) {
        this.sidebarOpen = true;
      }
    },
    setFilter(filter) {
      this.$store.dispatch('invoice/setFilter', filter)
    },

    updateSearchQuery() {
      this.$store.dispatch('invoice/setSearchQuery', this.searchQuery)
    },

    updateDateRange() {
      this.$store.dispatch('invoice/setDateRange', this.dateRange)
    },

 

    toggleState(state) {
      this.$store.dispatch('invoice/toggleState', state)
    },

    clearFilters() {
      this.searchQuery = ''
      this.dateRange = { start: '', end: '' }
      this.$store.dispatch('invoice/clearFilters')
    },

    logout() {
      this.$store.dispatch('auth/logout')
    },

    formatDate(dateString) {
      const date = new Date(dateString)
      return {
        date: date.toLocaleDateString('en-GB', {
          day: '2-digit',
          month: '2-digit',
          year: 'numeric'
        }),
        time: date.toLocaleTimeString('en-US', {
          hour: '2-digit',
          minute: '2-digit',
          hour12: true
        })
      }
    },

    viewInvoice(id) {
      this.$router.push(`/invoices/view/${id}`)
    },

    deleteInvoice(id) {
      if (confirm('Are you sure you want to delete this invoice?')) {
        this.$store.dispatch('invoice/deleteInvoice', id)
      }
    },

    editInvoice(id) {
      this.$router.push(`/invoices/edit/${id}`)
    },

    async fetchInvoices() {
      this.isLoading = true
      try {
        await this.$store.dispatch('invoice/fetchInvoices')
        console.log('Invoices fetched:', this.invoices)
      } catch (error) {
        console.error('Error fetching invoices:', error)
      } finally {
        this.isLoading = false
      }
    }
  },
  created() {
    this.fetchInvoices()
  },
  mounted() {
    // Check screen size on mount
    this.checkScreenSize();
    
    // Add resize event listener
    window.addEventListener('resize', this.checkScreenSize);
  },
  beforeDestroy() {
    // Clean up event listener
    window.removeEventListener('resize', this.checkScreenSize);
  }
}
</script>

<style scoped>
.filteration {
  gap: 10px;
}
.invoice-nav {
  box-shadow: 2px 2px 10px 0px #dbd6d6;

}
.main-content .text {
  font-size: 12px;
}
.table th {
  white-space: nowrap;
}
.table tr th {
  font-size: 12px;
  background: #CBE0EF;
  padding: 20px 10px;
}
.table tr td {
  font-size: 12.5px;
  font-weight: bold;
  padding: 30px 10px;
}
.search-input .input-group {
  border: 1px solid #ccc;
  border-radius: 50px;
  overflow: hidden;
}
.search-input .input-group input {
  border: none;
  outline: 0;
  box-shadow: none
}





@media (max-width: 767.98px) {
  .main-content {
    padding: 0 !important;
  }
  .invoice-nav{
    gap: 16px;
    padding: .5rem 5rem !important;
  }
}
@media (max-width: 575.98px) {
  .invoice-nav{
    gap: 12px;
    padding: .5rem 3rem !important;
  }
}
</style>